###
GET {{catalog_url}}/products

### Get all with paging
GET {{catalog_url}}/products?pageNumber=2&pageSize=2

###
PUT {{catalog_url}}/products
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
  "id": "6ec1297b-ec0a-4aa1-be25-6726e3b51a27",
  "name": "S",
  "Category": ["c1", "c2"],
  "description":"Description product C",
  "imageFile":"ImageFile product C",
  "Price":199    
}

###
POST {{catalog_url}}/products
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
  "name": "new product C",
  "Category": ["c1", "c2"],
  "description":"Description product C",
  "imageFile":"ImageFile product C",
  "Price":199    
}

###
@category = variable value
GET {{catalog_url}}/products/category/{{category}}

###
@id = variable value
GET {{catalog_url}}/products/{{id}}

###
DELETE {{catalog_url}}/products/{{id}}

### HealthCheck
DELETE {{catalog_url}}/health